(function(a,g,l){function e(b){m[b]||(m[b]=!0,a.migrateWarnings.push(b),g.console&&console.warn&&!a.migrateMute&&(console.warn("JQMIGRATE: "+b),a.migrateTrace&&console.trace&&console.trace()))}function h(b,c,d,k){if(Object.defineProperty)try{Object.defineProperty(b,c,{configurable:!0,enumerable:!0,get:function(){e(k);return d},set:function(a){e(k);d=a}});return}catch(f){}a._definePropertyBroken=!0;b[c]=d}var m={};a.migrateWarnings=[];!a.migrateMute&&g.console&&console.log&&console.log("JQMIGRATE: Logging is active");
void 0===a.migrateTrace&&(a.migrateTrace=!0);a.migrateReset=function(){m={};a.migrateWarnings.length=0};"BackCompat"===document.compatMode&&e("jQuery is not compatible with Quirks Mode");var p=a.attr,x=a.attrHooks.value&&a.attrHooks.value.get||function(){return null},y=a.attrHooks.value&&a.attrHooks.value.set||function(){},z=/^(?:input|button)$/i,A=/^[238]$/,B=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,C=/^(?:checked|selected)$/i;
h(a,"attrFn",{},"jQuery.attrFn is deprecated");a.attr=function(b,c,d,k){var f=c.toLowerCase(),g=b&&b.nodeType;if(k&&4>p.length&&(e("jQuery.fn.attr( props, pass ) is deprecated"),b&&!A.test(g)&&a.isFunction(a.fn[c])))return a(b)[c](d);"type"===c&&void 0!==d&&z.test(b.nodeName)&&b.parentNode&&e("Can't change the 'type' of an input or button in IE 6/7/8");!a.attrHooks[f]&&B.test(f)&&(a.attrHooks[f]={get:function(b,c){var d,e=a.prop(b,c);return!0===e||"boolean"!==typeof e&&(d=b.getAttributeNode(c))&&
!1!==d.nodeValue?c.toLowerCase():void 0},set:function(b,c,d){!1===c?a.removeAttr(b,d):(c=a.propFix[d]||d,c in b&&(b[c]=!0),b.setAttribute(d,d.toLowerCase()));return d}},C.test(f)&&e("jQuery.fn.attr('"+f+"') may use property instead of attribute"));return p.call(a,b,c,d)};a.attrHooks.value={get:function(a,c){var d=(a.nodeName||"").toLowerCase();if("button"===d)return x.apply(this,arguments);"input"!==d&&"option"!==d&&e("jQuery.fn.attr('value') no longer gets properties");return c in a?a.value:null},
set:function(a,c){var d=(a.nodeName||"").toLowerCase();if("button"===d)return y.apply(this,arguments);"input"!==d&&"option"!==d&&e("jQuery.fn.attr('value', val) no longer sets properties");a.value=c}};var n,q=a.fn.init,D=a.parseJSON,E=/^(?:[^<]*(<[\w\W]+>)[^>]*|#([\w\-]*))$/;a.fn.init=function(b,c,d){var k;return b&&"string"===typeof b&&!a.isPlainObject(c)&&(k=E.exec(b))&&k[1]&&("<"!==b.charAt(0)&&e("$(html) HTML strings must start with '<' character"),c&&c.context&&(c=c.context),a.parseHTML)?q.call(this,
a.parseHTML(a.trim(b),c,!0),c,d):q.apply(this,arguments)};a.fn.init.prototype=a.fn;a.parseJSON=function(a){return a||null===a?D.apply(this,arguments):(e("jQuery.parseJSON requires a valid JSON string"),null)};a.uaMatch=function(a){a=a.toLowerCase();a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}};
l=a.uaMatch(navigator.userAgent);n={};l.browser&&(n[l.browser]=!0,n.version=l.version);n.chrome?n.webkit=!0:n.webkit&&(n.safari=!0);a.browser=n;h(a,"browser",n,"jQuery.browser is deprecated");a.sub=function(){function b(a,c){return new b.fn.init(a,c)}a.extend(!0,b,this);b.superclass=this;b.fn=b.prototype=this();b.fn.constructor=b;b.sub=this.sub;b.fn.init=function(d,e){e&&e instanceof a&&!(e instanceof b)&&(e=b(e));return a.fn.init.call(this,d,e,c)};b.fn.init.prototype=b.fn;var c=b(document);e("jQuery.sub() is deprecated");
return b};var F=a.fn.data;a.fn.data=function(b){var c,d;return!(d=this[0])||"events"!==b||1!==arguments.length||(c=a.data(d,b),d=a._data(d,b),void 0!==c&&c!==d||void 0===d)?F.apply(this,arguments):(e("Use of jQuery.fn.data('events') is deprecated"),d)};var G=/\/(java|ecma)script/i,H=a.fn.andSelf||a.fn.addBack;a.fn.andSelf=function(){e("jQuery.fn.andSelf() replaced by jQuery.fn.addBack()");return H.apply(this,arguments)};a.clean||(a.clean=function(b,c,d,k){c=c||document;c=!c.nodeType&&c[0]||c;c=c.ownerDocument||
c;e("jQuery.clean() is deprecated");var f,g=[];a.merge(g,a.buildFragment(b,c).childNodes);if(d)for(c=function(a){if(!a.type||G.test(a.type))return k?k.push(a.parentNode?a.parentNode.removeChild(a):a):d.appendChild(a)},b=0;null!=(f=g[b]);b++)a.nodeName(f,"script")&&c(f)||(d.appendChild(f),"undefined"!==typeof f.getElementsByTagName&&(f=a.grep(a.merge([],f.getElementsByTagName("script")),c),g.splice.apply(g,[b+1,0].concat(f)),b+=f.length));return g});var I=a.event.add,J=a.event.remove,K=a.event.trigger,
L=a.fn.toggle,r=a.fn.live,t=a.fn.die,u=/\b(?:ajaxStart|ajaxStop|ajaxSend|ajaxComplete|ajaxError|ajaxSuccess)\b/,v=/(?:^|\s)hover(\.\S+|)\b/,w=function(b){if("string"!=typeof b||a.event.special.hover)return b;v.test(b)&&e("'hover' pseudo-event is deprecated, use 'mouseenter mouseleave'");return b&&b.replace(v,"mouseenter$1 mouseleave$1")};a.event.props&&"attrChange"!==a.event.props[0]&&a.event.props.unshift("attrChange","attrName","relatedNode","srcElement");a.event.dispatch&&h(a.event,"handle",a.event.dispatch,
"jQuery.event.handle is undocumented and deprecated");a.event.add=function(a,c,d,k,f){a!==document&&u.test(c)&&e("AJAX events should be attached to document: "+c);I.call(this,a,w(c||""),d,k,f)};a.event.remove=function(a,c,d,e,f){J.call(this,a,w(c)||"",d,e,f)};a.fn.error=function(){var a=Array.prototype.slice.call(arguments,0);e("jQuery.fn.error() is deprecated");a.splice(0,0,"error");if(arguments.length)return this.bind.apply(this,a);this.triggerHandler.apply(this,a);return this};a.fn.toggle=function(b,
c){if(!a.isFunction(b)||!a.isFunction(c))return L.apply(this,arguments);e("jQuery.fn.toggle(handler, handler...) is deprecated");var d=arguments,g=b.guid||a.guid++,f=0,h=function(c){var e=(a._data(this,"lastToggle"+b.guid)||0)%f;a._data(this,"lastToggle"+b.guid,e+1);c.preventDefault();return d[e].apply(this,arguments)||!1};for(h.guid=g;f<d.length;)d[f++].guid=g;return this.click(h)};a.fn.live=function(b,c,d){e("jQuery.fn.live() is deprecated");if(r)return r.apply(this,arguments);a(this.context).on(b,
this.selector,c,d);return this};a.fn.die=function(b,c){e("jQuery.fn.die() is deprecated");if(t)return t.apply(this,arguments);a(this.context).off(b,this.selector||"**",c);return this};a.event.trigger=function(a,c,d,g){!d&!u.test(a)&&e("Global events are undocumented and deprecated");return K.call(this,a,c,d||document,g)};a.each("ajaxStart ajaxStop ajaxSend ajaxComplete ajaxError ajaxSuccess".split(" "),function(b,c){a.event.special[c]={setup:function(){var b=this;b!==document&&(a.event.add(document,
c+"."+a.guid,function(){a.event.trigger(c,null,b,!0)}),a._data(this,c,a.guid++));return!1},teardown:function(){this!==document&&a.event.remove(document,c+"."+a._data(this,c));return!1}}})})(jQuery,window);
(function(a){var g;a.fn.jqprint=function(l){g=a.extend({},a.fn.jqprint.defaults,l);l=this instanceof jQuery?this:a(this);if(g.operaSupport&&a.browser.opera){var e=window.open("","jqPrint-preview");e.document.open();var h=e.document}else{var m=a("<iframe  />");g.debug||m.css({position:"absolute",width:"0px",height:"0px",left:"-600px",top:"-600px"});m.appendTo("body");h=m[0].contentWindow.document}g.importCSS&&(0<a("link[media=print]").length?a("link[media=print]").each(function(){h.write("<link type='text/css' rel='stylesheet' href='"+
a(this).attr("href")+"' media='print' />")}):a("link").each(function(){h.write("<link type='text/css' rel='stylesheet' href='"+a(this).attr("href")+"' />")}));g.printContainer?h.write(l.outer()):l.each(function(){h.write(a(this).html())});h.close();(g.operaSupport&&a.browser.opera?e:m[0].contentWindow).focus();setTimeout(function(){(g.operaSupport&&a.browser.opera?e:m[0].contentWindow).print();e&&e.close()},1E3)};a.fn.jqprint.defaults={debug:!1,importCSS:!0,printContainer:!0,operaSupport:!0};jQuery.fn.outer=
function(){return a(a("<div></div>").html(this.clone())).html()}})(jQuery);